
package org.fcrepo.apim;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Fedora-API-M", targetNamespace = "http://www.fedora.info/definitions/1/0/api/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FedoraAPIM {


    /**
     * 
     * @param objectXML
     * @param format
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#ingest")
    @WebResult(name = "objectPID", targetNamespace = "")
    @RequestWrapper(localName = "ingest", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.Ingest")
    @ResponseWrapper(localName = "ingestResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.IngestResponse")
    public String ingest(
        @WebParam(name = "objectXML", targetNamespace = "")
        byte[] objectXML,
        @WebParam(name = "format", targetNamespace = "")
        String format,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage);

    /**
     * 
     * @param ownerId
     * @param state
     * @param label
     * @param pid
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#modifyObject")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "modifyObject", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyObject")
    @ResponseWrapper(localName = "modifyObjectResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyObjectResponse")
    public String modifyObject(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "label", targetNamespace = "")
        String label,
        @WebParam(name = "ownerId", targetNamespace = "")
        String ownerId,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage);

    /**
     * 
     * @param pid
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getObjectXML")
    @WebResult(name = "objectXML", targetNamespace = "")
    @RequestWrapper(localName = "getObjectXML", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetObjectXML")
    @ResponseWrapper(localName = "getObjectXMLResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetObjectXMLResponse")
    public byte[] getObjectXML(
        @WebParam(name = "pid", targetNamespace = "")
        String pid);

    /**
     * 
     * @param context
     * @param pid
     * @param format
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#export")
    @WebResult(name = "objectXML", targetNamespace = "")
    @RequestWrapper(localName = "export", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.Export")
    @ResponseWrapper(localName = "exportResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ExportResponse")
    public byte[] export(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "format", targetNamespace = "")
        String format,
        @WebParam(name = "context", targetNamespace = "")
        String context);

    /**
     * 
     * @param pid
     * @param force
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#purgeObject")
    @WebResult(name = "purgedDate", targetNamespace = "")
    @RequestWrapper(localName = "purgeObject", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeObject")
    @ResponseWrapper(localName = "purgeObjectResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeObjectResponse")
    public String purgeObject(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage,
        @WebParam(name = "force", targetNamespace = "")
        boolean force);

    /**
     * 
     * @param altIDs
     * @param dsLocation
     * @param dsLabel
     * @param formatURI
     * @param checksumType
     * @param pid
     * @param checksum
     * @param controlGroup
     * @param versionable
     * @param dsID
     * @param dsState
     * @param mimeType
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#addDatastream")
    @WebResult(name = "datastreamID", targetNamespace = "")
    @RequestWrapper(localName = "addDatastream", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.AddDatastream")
    @ResponseWrapper(localName = "addDatastreamResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.AddDatastreamResponse")
    public String addDatastream(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "altIDs", targetNamespace = "")
        ArrayOfString altIDs,
        @WebParam(name = "dsLabel", targetNamespace = "")
        String dsLabel,
        @WebParam(name = "versionable", targetNamespace = "")
        boolean versionable,
        @WebParam(name = "MIMEType", targetNamespace = "")
        String mimeType,
        @WebParam(name = "formatURI", targetNamespace = "")
        String formatURI,
        @WebParam(name = "dsLocation", targetNamespace = "")
        String dsLocation,
        @WebParam(name = "controlGroup", targetNamespace = "")
        String controlGroup,
        @WebParam(name = "dsState", targetNamespace = "")
        String dsState,
        @WebParam(name = "checksumType", targetNamespace = "")
        String checksumType,
        @WebParam(name = "checksum", targetNamespace = "")
        String checksum,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage);

    /**
     * 
     * @param dsLocation
     * @param altIDs
     * @param dsLabel
     * @param dsID
     * @param formatURI
     * @param checksumType
     * @param pid
     * @param force
     * @param checksum
     * @param mimeType
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#modifyDatastreamByReference")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "modifyDatastreamByReference", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyDatastreamByReference")
    @ResponseWrapper(localName = "modifyDatastreamByReferenceResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyDatastreamByReferenceResponse")
    public String modifyDatastreamByReference(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "altIDs", targetNamespace = "")
        ArrayOfString altIDs,
        @WebParam(name = "dsLabel", targetNamespace = "")
        String dsLabel,
        @WebParam(name = "MIMEType", targetNamespace = "")
        String mimeType,
        @WebParam(name = "formatURI", targetNamespace = "")
        String formatURI,
        @WebParam(name = "dsLocation", targetNamespace = "")
        String dsLocation,
        @WebParam(name = "checksumType", targetNamespace = "")
        String checksumType,
        @WebParam(name = "checksum", targetNamespace = "")
        String checksum,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage,
        @WebParam(name = "force", targetNamespace = "")
        boolean force);

    /**
     * 
     * @param altIDs
     * @param dsContent
     * @param dsLabel
     * @param dsID
     * @param formatURI
     * @param checksumType
     * @param pid
     * @param force
     * @param checksum
     * @param mimeType
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#modifyDatastreamByValue")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "modifyDatastreamByValue", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyDatastreamByValue")
    @ResponseWrapper(localName = "modifyDatastreamByValueResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ModifyDatastreamByValueResponse")
    public String modifyDatastreamByValue(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "altIDs", targetNamespace = "")
        ArrayOfString altIDs,
        @WebParam(name = "dsLabel", targetNamespace = "")
        String dsLabel,
        @WebParam(name = "MIMEType", targetNamespace = "")
        String mimeType,
        @WebParam(name = "formatURI", targetNamespace = "")
        String formatURI,
        @WebParam(name = "dsContent", targetNamespace = "")
        byte[] dsContent,
        @WebParam(name = "checksumType", targetNamespace = "")
        String checksumType,
        @WebParam(name = "checksum", targetNamespace = "")
        String checksum,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage,
        @WebParam(name = "force", targetNamespace = "")
        boolean force);

    /**
     * 
     * @param dsID
     * @param dsState
     * @param pid
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#setDatastreamState")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "setDatastreamState", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.SetDatastreamState")
    @ResponseWrapper(localName = "setDatastreamStateResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.SetDatastreamStateResponse")
    public String setDatastreamState(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "dsState", targetNamespace = "")
        String dsState,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage);

    /**
     * 
     * @param versionable
     * @param dsID
     * @param pid
     * @param logMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#setDatastreamVersionable")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "setDatastreamVersionable", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.SetDatastreamVersionable")
    @ResponseWrapper(localName = "setDatastreamVersionableResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.SetDatastreamVersionableResponse")
    public String setDatastreamVersionable(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "versionable", targetNamespace = "")
        boolean versionable,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage);

    /**
     * 
     * @param dsID
     * @param versionDate
     * @param pid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#compareDatastreamChecksum")
    @WebResult(name = "checksum", targetNamespace = "")
    @RequestWrapper(localName = "compareDatastreamChecksum", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.CompareDatastreamChecksum")
    @ResponseWrapper(localName = "compareDatastreamChecksumResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.CompareDatastreamChecksumResponse")
    public String compareDatastreamChecksum(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "versionDate", targetNamespace = "")
        String versionDate);

    /**
     * 
     * @param dsID
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns org.fcrepo.apim.Datastream
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDatastream")
    @WebResult(name = "datastream", targetNamespace = "")
    @RequestWrapper(localName = "getDatastream", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastream")
    @ResponseWrapper(localName = "getDatastreamResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastreamResponse")
    public Datastream getDatastream(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param dsState
     * @param pid
     * @return
     *     returns java.util.List<org.fcrepo.apim.Datastream>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDatastreams")
    @WebResult(name = "datastream", targetNamespace = "")
    @RequestWrapper(localName = "getDatastreams", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastreams")
    @ResponseWrapper(localName = "getDatastreamsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastreamsResponse")
    public List<Datastream> getDatastreams(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime,
        @WebParam(name = "dsState", targetNamespace = "")
        String dsState);

    /**
     * 
     * @param dsID
     * @param pid
     * @return
     *     returns java.util.List<org.fcrepo.apim.Datastream>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDatastreamHistory")
    @WebResult(name = "datastream", targetNamespace = "")
    @RequestWrapper(localName = "getDatastreamHistory", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastreamHistory")
    @ResponseWrapper(localName = "getDatastreamHistoryResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetDatastreamHistoryResponse")
    public List<Datastream> getDatastreamHistory(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID);

    /**
     * 
     * @param endDT
     * @param dsID
     * @param startDT
     * @param pid
     * @param force
     * @param logMessage
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#purgeDatastream")
    @WebResult(name = "purgedVersionDate", targetNamespace = "")
    @RequestWrapper(localName = "purgeDatastream", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeDatastream")
    @ResponseWrapper(localName = "purgeDatastreamResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeDatastreamResponse")
    public List<String> purgeDatastream(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "startDT", targetNamespace = "")
        String startDT,
        @WebParam(name = "endDT", targetNamespace = "")
        String endDT,
        @WebParam(name = "logMessage", targetNamespace = "")
        String logMessage,
        @WebParam(name = "force", targetNamespace = "")
        boolean force);

    /**
     * 
     * @param numPIDs
     * @param pidNamespace
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getNextPID")
    @WebResult(name = "pid", targetNamespace = "")
    @RequestWrapper(localName = "getNextPID", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetNextPID")
    @ResponseWrapper(localName = "getNextPIDResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetNextPIDResponse")
    public List<String> getNextPID(
        @WebParam(name = "numPIDs", targetNamespace = "")
        BigInteger numPIDs,
        @WebParam(name = "pidNamespace", targetNamespace = "")
        String pidNamespace);

    /**
     * 
     * @param relationship
     * @param pid
     * @return
     *     returns java.util.List<org.fcrepo.apim.RelationshipTuple>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getRelationships")
    @WebResult(name = "relationships", targetNamespace = "")
    @RequestWrapper(localName = "getRelationships", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetRelationships")
    @ResponseWrapper(localName = "getRelationshipsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.GetRelationshipsResponse")
    public List<RelationshipTuple> getRelationships(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "relationship", targetNamespace = "")
        String relationship);

    /**
     * 
     * @param relationship
     * @param isLiteral
     * @param pid
     * @param datatype
     * @param object
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#addRelationship")
    @WebResult(name = "added", targetNamespace = "")
    @RequestWrapper(localName = "addRelationship", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.AddRelationship")
    @ResponseWrapper(localName = "addRelationshipResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.AddRelationshipResponse")
    public boolean addRelationship(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "relationship", targetNamespace = "")
        String relationship,
        @WebParam(name = "object", targetNamespace = "")
        String object,
        @WebParam(name = "isLiteral", targetNamespace = "")
        boolean isLiteral,
        @WebParam(name = "datatype", targetNamespace = "")
        String datatype);

    /**
     * 
     * @param relationship
     * @param isLiteral
     * @param pid
     * @param datatype
     * @param object
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#purgeRelationship")
    @WebResult(name = "purged", targetNamespace = "")
    @RequestWrapper(localName = "purgeRelationship", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeRelationship")
    @ResponseWrapper(localName = "purgeRelationshipResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.PurgeRelationshipResponse")
    public boolean purgeRelationship(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "relationship", targetNamespace = "")
        String relationship,
        @WebParam(name = "object", targetNamespace = "")
        String object,
        @WebParam(name = "isLiteral", targetNamespace = "")
        boolean isLiteral,
        @WebParam(name = "datatype", targetNamespace = "")
        String datatype);

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns org.fcrepo.apim.Validation
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#validate")
    @WebResult(name = "validation", targetNamespace = "")
    @RequestWrapper(localName = "validate", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.Validate")
    @ResponseWrapper(localName = "validateResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apim.ValidateResponse")
    public Validation validate(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

}
