
package org.fcrepo.apia;

import java.math.BigInteger;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Fedora-API-A", targetNamespace = "http://www.fedora.info/definitions/1/0/api/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FedoraAPIA {


    /**
     * 
     * @return
     *     returns org.fcrepo.apia.RepositoryInfo
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#describeRepository")
    @WebResult(name = "repositoryInfo", targetNamespace = "")
    @RequestWrapper(localName = "describeRepository", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.DescribeRepository")
    @ResponseWrapper(localName = "describeRepositoryResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.DescribeRepositoryResponse")
    public RepositoryInfo describeRepository();

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns org.fcrepo.apia.ObjectProfile
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getObjectProfile")
    @WebResult(name = "objectProfile", targetNamespace = "")
    @RequestWrapper(localName = "getObjectProfile", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetObjectProfile")
    @ResponseWrapper(localName = "getObjectProfileResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetObjectProfileResponse")
    public ObjectProfile getObjectProfile(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns java.util.List<org.fcrepo.apia.ObjectMethodsDef>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#listMethods")
    @WebResult(name = "objectMethod", targetNamespace = "")
    @RequestWrapper(localName = "listMethods", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ListMethods")
    @ResponseWrapper(localName = "listMethodsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ListMethodsResponse")
    public List<ObjectMethodsDef> listMethods(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns java.util.List<org.fcrepo.apia.DatastreamDef>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#listDatastreams")
    @WebResult(name = "datastreamDef", targetNamespace = "")
    @RequestWrapper(localName = "listDatastreams", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ListDatastreams")
    @ResponseWrapper(localName = "listDatastreamsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ListDatastreamsResponse")
    public List<DatastreamDef> listDatastreams(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param dsID
     * @param asOfDateTime
     * @param pid
     * @return
     *     returns org.fcrepo.apia.MIMETypedStream
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDatastreamDissemination")
    @WebResult(name = "dissemination", targetNamespace = "")
    @RequestWrapper(localName = "getDatastreamDissemination", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetDatastreamDissemination")
    @ResponseWrapper(localName = "getDatastreamDisseminationResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetDatastreamDisseminationResponse")
    public MIMETypedStream getDatastreamDissemination(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "dsID", targetNamespace = "")
        String dsID,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param serviceDefinitionPid
     * @param asOfDateTime
     * @param pid
     * @param parameters
     * @param methodName
     * @return
     *     returns org.fcrepo.apia.MIMETypedStream
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getDissemination")
    @WebResult(name = "dissemination", targetNamespace = "")
    @RequestWrapper(localName = "getDissemination", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetDissemination")
    @ResponseWrapper(localName = "getDisseminationResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetDisseminationResponse")
    public MIMETypedStream getDissemination(
        @WebParam(name = "pid", targetNamespace = "")
        String pid,
        @WebParam(name = "serviceDefinitionPid", targetNamespace = "")
        String serviceDefinitionPid,
        @WebParam(name = "methodName", targetNamespace = "")
        String methodName,
        @WebParam(name = "parameters", targetNamespace = "")
        org.fcrepo.apia.GetDissemination.Parameters parameters,
        @WebParam(name = "asOfDateTime", targetNamespace = "")
        String asOfDateTime);

    /**
     * 
     * @param query
     * @param resultFields
     * @param maxResults
     * @return
     *     returns org.fcrepo.apia.FieldSearchResult
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#findObjects")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "findObjects", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.FindObjects")
    @ResponseWrapper(localName = "findObjectsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.FindObjectsResponse")
    public FieldSearchResult findObjects(
        @WebParam(name = "resultFields", targetNamespace = "")
        ArrayOfString resultFields,
        @WebParam(name = "maxResults", targetNamespace = "")
        BigInteger maxResults,
        @WebParam(name = "query", targetNamespace = "")
        FieldSearchQuery query);

    /**
     * 
     * @param sessionToken
     * @return
     *     returns org.fcrepo.apia.FieldSearchResult
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#resumeFindObjects")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "resumeFindObjects", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ResumeFindObjects")
    @ResponseWrapper(localName = "resumeFindObjectsResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.ResumeFindObjectsResponse")
    public FieldSearchResult resumeFindObjects(
        @WebParam(name = "sessionToken", targetNamespace = "")
        String sessionToken);

    /**
     * 
     * @param pid
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "http://www.fedora.info/definitions/1/0/api/#getObjectHistory")
    @WebResult(name = "modifiedDate", targetNamespace = "")
    @RequestWrapper(localName = "getObjectHistory", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetObjectHistory")
    @ResponseWrapper(localName = "getObjectHistoryResponse", targetNamespace = "http://www.fedora.info/definitions/1/0/types/", className = "org.fcrepo.apia.GetObjectHistoryResponse")
    public List<String> getObjectHistory(
        @WebParam(name = "pid", targetNamespace = "")
        String pid);

}
